default_language_version:
  python: python3.8
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: mixed-line-ending

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black

  - repo: https://github.com/timothycrosley/isort
    rev: 5.13.2
    hooks:
      - id: isort

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear]

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.8.7
    hooks:
      - id: nbqa-black
        additional_dependencies: [black==24.8.0]
      - id: nbqa-isort
        additional_dependencies: [isort==5.13.2]
      - id: nbqa-flake8
        additional_dependencies: [flake8==7.1.1]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or: [markdown, yaml, toml, json, dockerfile, shell]
        additional_dependencies: ["prettier@3.1.0", "prettier-plugin-sh@0.13.1"]
        args: [--print-width=80, --prose-wrap=always]

  - repo: local
    hooks:
      - id: backslash-fixer
        name: Fix backslashes in Jupyter Notebooks
        description:
          Replaces all the backslashes in notebook's markdown cells to break
          tag.
        entry: python commands.py backslash_fix
        additional_dependencies: [fire]
        language: python
        types: [jupyter]
